---
# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks

fail_fast: false
repos:
  - repo: https://github.com/adrienverge/yamllint.git
    rev: v1.35.1
    hooks:
      - id: yamllint
        args:
          - --config-file
          - .github/linters/.yamllint.yaml
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.6.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: mixed-line-ending
      - id: detect-private-key
      - id: sort-simple-yaml
  - repo: https://github.com/Lucas-C/pre-commit-hooks
    rev: v1.5.5
    hooks:
      - id: forbid-crlf
      - id: forbid-tabs
      - id: remove-crlf
      - id: remove-tabs
  - repo: https://github.com/sirosen/fix-smartquotes
    rev: 0.2.0
    hooks:
      - id: fix-smartquotes
  - repo: https://github.com/k8s-at-home/sops-pre-commit
    rev: v2.1.1
    hooks:
      - id: forbid-secrets
  - repo: https://github.com/igorshubovych/markdownlint-cli
    rev: v0.41.0
    hooks:
      - id: markdownlint
        args:
          - --config
          - '.github/linters/.markdownlint.yaml'
  - repo: https://github.com/python-jsonschema/check-jsonschema
    rev: 0.29.2
    hooks:
      - id: check-renovate
  - repo: https://github.com/zricethezav/gitleaks
    rev: v8.18.4
    hooks:
      - id: gitleaks
  - repo: https://github.com/tekwizely/pre-commit-golang
    rev: v1.0.0-rc.1
    hooks:
      - id: go-mod-tidy
      - id: go-mod-tidy-repo
      - id: go-revive
      - id: go-revive-mod
      - id: go-revive-repo-mod
      - id: go-sec-mod
      - id: go-sec-pkg
      - id: go-sec-repo-mod
      - id: go-sec-repo-pkg
      - id: go-staticcheck-mod
      - id: go-staticcheck-pkg
      - id: go-staticcheck-repo-mod
      - id: go-staticcheck-repo-pkg
      - id: go-structslop-mod
      - id: go-structslop-pkg
      - id: go-structslop-repo-mod
      - id: go-structslop-repo-pkg
      - id: go-fumpt        # replaces go-fmt
      - id: go-fumpt-repo   # replaces go-fmt-repo
      - id: go-lint
      - id: go-critic
      - id: golangci-lint
      - id: golangci-lint-mod
      - id: golangci-lint-pkg
      - id: golangci-lint-repo-mod
      - id: golangci-lint-repo-pkg
  - repo: https://github.com/hadolint/hadolint
    rev: v2.12.0
    hooks:
      - id: hadolint-docker
        args:
          - goreleaser.Dockerfile
      - id: hadolint
        args:
          - goreleaser.Dockerfile
